version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  build:
    commands:
      - echo "Fetching AWS Account ID..."
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - S3_BUCKET="my-codepipeline-artifacts-${ACCOUNT_ID}"
      - echo "Using S3 Bucket: $S3_BUCKET"

      - echo "Zipping Lambda function code..."
      - zip -r lambda-code.zip lambda_function.py

      - echo "Uploading Lambda package to S3 artifact bucket..."
      - aws s3 cp lambda-code.zip s3://$S3_BUCKET/

artifacts:
  files:
    - lambda-code.zip
    - simplelambda.yaml
